### ISSUE TITLE
Grunt full

### ISSUE THREAD

**Issue by creativecaptain** [ALT-F1/bootstrap3-jade-node-express-grunt#6]
How to get the changes of less files in the output
as I know, in my previous project I used "grunt full", as I am new to this technology, can you please help me in this?

**Comment by Abdelkrim** [comment]
sorry @creativecaptain but I don't understand the question.

**Comment by Abdelkrim** [comment]
I close the issue since @creativecaptain didn't reply to my question 9 months ago
